from pathlib import Path
import json
import shutil
import random


# ============================================================
# SIDTD 41-CLASS -> 7-CLASS YOLO DATASET
# ============================================================

# Project root:
# D:\veridex
ROOT = Path(__file__).resolve().parent.parent

# Actual SIDTD location
SIDTD = ROOT / "dataset" / "SIDTD"

# Existing YOLO annotations
SOURCE_LABELS = SIDTD / "yolo_annotations"

# Existing images
SOURCE_IMAGES = SIDTD / "annotated_fakes"

# Class mapping generated by the SIDTD annotator
CLASSES_JSON = SIDTD / "classes.json"

# New dataset
OUTPUT = ROOT / "dataset" / "SIDTD_yolo_grouped"

TRAIN_RATIO = 0.80
SEED = 42


# ============================================================
# GROUPING
# ============================================================

GROUPS = {
    "name": 0,
    "surname": 0,
    "surname_eng": 0,
    "surname_second": 0,
    "name_eng": 0,
    "patronymic": 0,
    "name_code": 0,

    "birth_date": 1,
    "birth_date_2": 1,
    "birth_date_22": 1,

    "expiry_date": 2,
    "expiry_date2": 2,
    "expiry_date_2": 2,

    "number": 3,
    "number2": 3,
    "number3": 3,
    "id_number": 3,

    "photo": 4,

    "signature": 5,

    # Everything else
    "authority": 6,
    "authority_eng": 6,
    "authority_line0": 6,
    "authority_line1": 6,
    "birth_country": 6,
    "birth_place": 6,
    "birth_place_eng": 6,
    "birth_place_line0": 6,
    "birth_place_line1": 6,
    "birth_place_line2": 6,
    "code": 6,
    "gender": 6,
    "height": 6,
    "issue_date": 6,
    "issue_place": 6,
    "mrz_line0": 6,
    "mrz_line1": 6,
    "nationality": 6,
    "nationality/nationality_eng": 6,
    "residence_line0": 6,
    "residence_line1": 6,
    "type": 6,
}


CLASS_NAMES = [
    "name",
    "birth_date",
    "expiry_date",
    "number",
    "photo",
    "signature",
    "other",
]


# ============================================================
# HELPERS
# ============================================================

def load_classes():
    if not CLASSES_JSON.exists():
        raise FileNotFoundError(
            f"\nCould not find:\n{CLASSES_JSON}\n"
            f"\nExpected classes.json directly inside:\n{SIDTD}\n"
        )

    with CLASSES_JSON.open("r", encoding="utf-8") as f:
        data = json.load(f)

    # classes.json is expected to be:
    #
    # {
    #   "field_name": class_id
    # }
    #
    # Convert IDs to integers just in case.
    return {str(k): int(v) for k, v in data.items()}


def find_image(stem):
    """
    Find image corresponding to a YOLO label.

    Checks annotated_fakes first, then Images/fakes.
    """

    extensions = [
        ".jpg",
        ".jpeg",
        ".png",
        ".JPG",
        ".JPEG",
        ".PNG",
    ]

    locations = [
        SOURCE_IMAGES,
        SIDTD / "Images" / "fakes",
    ]

    for directory in locations:
        if not directory.exists():
            continue

        for ext in extensions:
            path = directory / (stem + ext)

            if path.exists():
                return path

    # Recursive fallback
    for directory in locations:
        if not directory.exists():
            continue

        for path in directory.rglob("*"):
            if not path.is_file():
                continue

            if path.suffix.lower() not in {".jpg", ".jpeg", ".png"}:
                continue

            if path.stem.lower() == stem.lower():
                return path

    return None


def convert_label(label_path, old_to_new):
    """
    Convert a YOLO label file from the original 41 classes
    to the new 7-class grouping.

    If multiple original boxes belong to the same grouped class,
    all boxes are preserved.
    """

    output_lines = []

    with label_path.open("r", encoding="utf-8") as f:
        lines = f.readlines()

    for line in lines:
        line = line.strip()

        if not line:
            continue

        parts = line.split()

        if len(parts) != 5:
            print(
                f"[WARNING] Invalid YOLO line in {label_path.name}: {line}"
            )
            continue

        try:
            old_class = int(parts[0])
        except ValueError:
            print(
                f"[WARNING] Invalid class ID in {label_path.name}: {line}"
            )
            continue

        if old_class not in old_to_new:
            print(
                f"[WARNING] No grouping for original class "
                f"{old_class} in {label_path.name}"
            )
            continue

        new_class = old_to_new[old_class]

        output_lines.append(
            f"{new_class} "
            f"{parts[1]} "
            f"{parts[2]} "
            f"{parts[3]} "
            f"{parts[4]}"
        )

    return output_lines


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 60)
    print("SIDTD 41-CLASS -> 7-CLASS YOLO DATASET")
    print("=" * 60)

    print(f"ROOT          : {ROOT}")
    print(f"SIDTD         : {SIDTD}")
    print(f"Classes       : {CLASSES_JSON}")
    print(f"Labels        : {SOURCE_LABELS}")
    print(f"Images        : {SOURCE_IMAGES}")
    print(f"Output        : {OUTPUT}")
    print()

    # --------------------------------------------------------
    # Validate directories
    # --------------------------------------------------------

    if not SIDTD.exists():
        raise FileNotFoundError(f"SIDTD directory not found:\n{SIDTD}")

    if not SOURCE_LABELS.exists():
        raise FileNotFoundError(
            f"YOLO annotations not found:\n{SOURCE_LABELS}"
        )

    if not CLASSES_JSON.exists():
        raise FileNotFoundError(
            f"classes.json not found:\n{CLASSES_JSON}"
        )

    # --------------------------------------------------------
    # Load original classes
    # --------------------------------------------------------

    classes = load_classes()

    print(f"Original classes found: {len(classes)}")
    print()

    # --------------------------------------------------------
    # Build old class ID -> new class ID mapping
    # --------------------------------------------------------

    old_to_new = {}

    missing = []

    for class_name, old_id in classes.items():

        if class_name not in GROUPS:
            missing.append(class_name)
            continue

        old_to_new[old_id] = GROUPS[class_name]

    if missing:
        print("[WARNING] These classes have no explicit grouping:")

        for name in missing:
            print(f"  - {name}")

        print()
        print("They will be ignored.")
        print()

    print("GROUPING:")
    print("-" * 40)

    for i, name in enumerate(CLASS_NAMES):
        members = [
            k for k, v in GROUPS.items()
            if v == i
        ]

        print(f"{i}: {name}")
        print(f"   {', '.join(members)}")

    print()

    # --------------------------------------------------------
    # Find labels
    # --------------------------------------------------------

    label_files = sorted(SOURCE_LABELS.rglob("*.txt"))

    if not label_files:
        raise FileNotFoundError(
            f"No YOLO .txt labels found in:\n{SOURCE_LABELS}"
        )

    print(f"Found {len(label_files)} label files.")
    print()

    # --------------------------------------------------------
    # Match labels to images
    # --------------------------------------------------------

    pairs = []

    for label_path in label_files:

        stem = label_path.stem

        image_path = find_image(stem)

        if image_path is None:
            print(
                f"[WARNING] Image not found for label: "
                f"{label_path.name}"
            )
            continue

        pairs.append((image_path, label_path))

    print(f"Found {len(pairs)} image/label pairs.")

    if not pairs:
        raise RuntimeError("No image/label pairs found.")

    # --------------------------------------------------------
    # Shuffle and split
    # --------------------------------------------------------

    random.seed(SEED)
    random.shuffle(pairs)

    split = int(len(pairs) * TRAIN_RATIO)

    train_pairs = pairs[:split]
    val_pairs = pairs[split:]

    print(f"Train: {len(train_pairs)}")
    print(f"Val  : {len(val_pairs)}")
    print()

    # --------------------------------------------------------
    # Recreate output directories
    # --------------------------------------------------------

    if OUTPUT.exists():
        print(f"Removing existing output:\n{OUTPUT}")
        shutil.rmtree(OUTPUT)

    train_images = OUTPUT / "images" / "train"
    val_images = OUTPUT / "images" / "val"

    train_labels = OUTPUT / "labels" / "train"
    val_labels = OUTPUT / "labels" / "val"

    for directory in [
        train_images,
        val_images,
        train_labels,
        val_labels,
    ]:
        directory.mkdir(parents=True, exist_ok=True)

    # --------------------------------------------------------
    # Process dataset
    # --------------------------------------------------------

    def process_split(pairs, image_dir, label_dir):

        processed = 0

        for image_path, label_path in pairs:

            # Copy image
            destination_image = image_dir / image_path.name
            shutil.copy2(image_path, destination_image)

            # Convert labels
            new_lines = convert_label(
                label_path,
                old_to_new
            )

            # Write grouped labels
            destination_label = (
                label_dir / f"{image_path.stem}.txt"
            )

            with destination_label.open(
                "w",
                encoding="utf-8"
            ) as f:

                if new_lines:
                    f.write("\n".join(new_lines) + "\n")

            processed += 1

        return processed

    print("Processing training set...")

    train_count = process_split(
        train_pairs,
        train_images,
        train_labels
    )

    print(f"Processed: {train_count}")

    print()
    print("Processing validation set...")

    val_count = process_split(
        val_pairs,
        val_images,
        val_labels
    )

    print(f"Processed: {val_count}")

    # --------------------------------------------------------
    # Write data.yaml
    # --------------------------------------------------------

    yaml_path = OUTPUT / "data.yaml"

    yaml_content = f"""path: {OUTPUT.as_posix()}
train: images/train
val: images/val

nc: {len(CLASS_NAMES)}

names:
"""

    for i, name in enumerate(CLASS_NAMES):
        yaml_content += f"  {i}: {name}\n"

    yaml_path.write_text(
        yaml_content,
        encoding="utf-8"
    )

    # --------------------------------------------------------
    # Write classes.txt
    # --------------------------------------------------------

    (OUTPUT / "classes.txt").write_text(
        "\n".join(CLASS_NAMES) + "\n",
        encoding="utf-8"
    )

    # --------------------------------------------------------
    # Done
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("DATASET CREATED")
    print("=" * 60)

    print(f"Train images : {train_count}")
    print(f"Val images   : {val_count}")
    print()
    print(f"Dataset: {OUTPUT}")
    print(f"YAML   : {yaml_path}")
    print()
    print("Classes:")

    for i, name in enumerate(CLASS_NAMES):
        print(f"  {i}: {name}")

    print("=" * 60)


if __name__ == "__main__":
    main()